apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: asset-spy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "200m"
            requests:
              memory: "256Mi"
              cpu: "100m"
          env:
            - name: POSTGRES_DB
              value: "asset_spy_db"
            - name: POSTGRES_PASSWORD
              value: "123"
            - name: POSTGRES_USER
              value: "postgres"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
            - mountPath: /docker-entrypoint-initdb.d
              name: init-sql-volume
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init-sql-volume
          configMap:
            name: postgres-init-sql