apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-pv
  namespace: asset-spy
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/pgadmin"