apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: asset-spy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 5050:5050 /var/lib/pgadmin && chmod -R 755 /var/lib/pgadmin"]
          volumeMounts:
            - mountPath: /var/lib/pgadmin
              name: pgadmin-data
      securityContext:
        runAsUser: 0
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          securityContext:
            runAsUser: 5050
            runAsGroup: 5050
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "64Mi"
              cpu: "50m"
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "admin@admin.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "123"
          volumeMounts:
            - mountPath: /var/lib/pgadmin
              name: pgadmin-data
      volumes:
        - name: pgadmin-data
          persistentVolumeClaim:
            claimName: pgadmin-pvc